// Conventional Commits with explicit scopes aligned to the monorepo layout.
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'chore', 'build', 'ci', 'revert'],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'monorepo',
        'web',
        'storybook',
        'api-gateway',
        'iam',
        'device',
        'connector',
        'ingest',
        'historian',
        'event-detection',
        'alarm',
        'reporting',
        'geo',
        'audit',
        'notification',
        'shared-modbus',
        'shared-events',
        'shared-domain',
        'shared-config',
        'shared-types',
        'infra',
        'db',
        'docs',
        'ci',
        'security',
        'ux',
      ],
    ],
    'subject-case': [0],
  },
};
